### ISSUE TITLE
[2pt] Style guide: don't use "=<>" as words.

### ISSUE THREAD

**Issue by NickVolynkin** [tarantool/doc#1886] opened 2021-03-01 12:40 UTC
# Discourage using "=<>" and other operators in place of words

It's almost as 👎 as using emojis in place of words. 💯 % bad!

Use "equals", "doesn't equal" and other words, or format the whole expression as code.

**Reviewer:** @NickVolynkin 

Example: https://www.tarantool.io/en/doc/latest/reference/reference_lua/box_space/update/

<img width="980" alt="Screenshot 2021-03-01 at 19 37 12" src="https://user-images.githubusercontent.com/8015154/109498206-bc3a1080-7ac5-11eb-872e-c2c47a44a5ed.png">

# DoD

- [ ] Update the style guide

**Comment by Onvember** [comment] 2021-04-14 09:33
Duplicate of #1835

**Closed by Onvember** 2021-04-14 09:33 UTC
Labels: internal
