### ISSUE TITLE
Describe the 'box.info.synchro' and 'box.info.synchro.queue' fields

### ISSUE THREAD

**Issue by rindblack15** [tarantool/doc#2871] opened 2022-05-16 06:03 UTC
**Related dev. issue(s):** 

**Product:** Tarantool
**Since:** 2.10.0-rc1
**Root document:** https://www.tarantool.io/ru/doc/latest/reference/reference_lua/box_info/
**SME:** @ sergepetrenko

# Details

There is no information about the 'box.info.synchro' and 'box.info.synchro.queue' fields, you need to describe them in Submodule box.info.

# Definition of done

- [ ] Request details from @ sergepetrenko.
- [ ] Description  'box.info.synchro' and 'box.info.synchro.queue' added to Submodule box.info.

# Important
This issue is connected to https://github.com/tarantool/doc/issues/2831.

**Comment by xuniq** [comment] 2022-09-14 14:50
Duplicate of #2044

**Closed as completed by xuniq** 2022-09-14 14:50 UTC
Labels: reference, server, add details, dev
