### ISSUE TITLE
Document feedback daemon in 1.10

### ISSUE THREAD

**Issue by kostja** [tarantool/doc#445] opened 2018-03-05 06:09 UTC
The issue itself is reported here: https://github.com/tarantool/tarantool/issues/2762 
@IlyaMarkovMipt should be able to provide implementation details.

**Comment by lenkis** [comment] 2018-03-26 16:38
Duplicate of https://github.com/tarantool/doc/issues/470

**Closed by lenkis** 2018-03-26 16:38 UTC
Labels: 1.10, low_priority
