### ISSUE TITLE
need to add more instructions on Tarantool download for different versions

### ISSUE THREAD

**Issue by avtikhon** [tarantool/doc#1337] opened 2020-05-25 12:17 UTC
Need to have:
2.2 Stable
2.3 Stable
2.4 Beta
1.10 LTS

**Comment by artur-barsegyan** [comment] 2020-08-07 15:45
After some discussions with @artembo we've decided to implement the next layout:

Example for Linux-like distros:

- Text that describes differences between 2.x and 1.10.x branches
- Stable versions
> 2.3
```bash
apt-get -y install sudo
sudo apt-get -y install gnupg2
sudo apt-get -y install curl

curl https://download.tarantool.org/tarantool/release/2.2/gpgkey | sudo apt-key add -
...

# install tarantool
sudo apt-get -y update
sudo apt-get -y install tarantool
```
> 2.2
> 1.10


Live versions
> 2.5
> 2.4

_________

The lines with versions are clickable. After a click, the version should be expanded and instruction should be visible below. You can watch the example with version 2.3.

**Comment by Totktonada** [comment] 2020-08-07 16:24
@artur-barsegyan Stable → release. They are different terms. There are releases, which are not stable (alpha and beta). If you'll enable 2.5 repository now, the most fresh package, which it'll contain, is 2.5.1 (beta).

**Comment by artembo** [comment] 2020-08-14 14:13
This page is going to be redesigned completely, so I updated 2.2 version to 2.5 as a temporary solution.

Another idea about this page is to implement an automated updating the list of active versions after the new tarantool version is released.

**Comment by Totktonada** [comment] 2020-11-09 01:50
Are there any further actions planned to be performed within the scope of this issue?

**Comment by artur-barsegyan** [comment] 2020-11-12 17:50
> Are there any further actions planned to be performed within the scope of this issue?

The issue is done. We can close it.

**Closed by artur-barsegyan** 2020-11-12 17:50 UTC
Labels: download
