### ISSUE TITLE
All tarantool.org links in awesome-tarantool are broken

### ISSUE THREAD

**Issue by Totktonada** [tarantool/doc#2336] opened 2021-09-18 18:02 UTC
See https://github.com/tarantool/awesome-tarantool/pull/6

Finally, please, implement #1678. Now the website is useless: I cannot paste a link to any article, because it'll be 404 soon.

**Comment by patiencedaur** [comment] 2022-05-19 13:04
Checked the links in awesome-tarantool pointing to the doc site. Looks like the issue is fixed. Closing.

**Closed by patiencedaur** 2022-05-19 13:04 UTC
