### ISSUE TITLE
Version drop-down menu defect

### ISSUE THREAD

**Issue by bigbes** [tarantool/doc#230] opened 2017-06-23 17:31 UTC
* Menu is ripped (but it shouldn't exists at all - https://tarantool.org/en/doc/1.8/index.html#):
  ![image](https://user-images.githubusercontent.com/495636/27493501-c50b2206-5852-11e7-9c32-8d5a04b85d19.png)

* Menu lost one item (for example - here https://tarantool.org/en/doc/1.8/whats_new.html#what-s-new-in-tarantool-1-8):
  ![image](https://user-images.githubusercontent.com/495636/27493586-d37497e6-5852-11e7-91fa-b5a39c4ded29.png)

**Comment by lenkis** [comment] 2017-06-26 07:19
item (2) is duplicate of gh-226

**Comment by lenkis** [comment] 2017-06-26 07:59
Fixed by PR merge https://github.com/tarantool/doc/pull/228

**Comment by bigbes** [comment] 2017-06-26 11:07
item (2) is duplicate, but problem with top menu https://tarantool.org/doc/1.7/index.html still exists

**Comment by lenkis** [comment] 2017-06-26 13:27
item (1) is duplicate of #231. closing this issue to avoid confusion.

**Closed by lenkis** 2017-06-26 13:27 UTC
Labels: bug, design, LT, tarantool.org
