### ISSUE TITLE
[0pt] Fix {release for site tarantool.io}

### ISSUE THREAD

**Issue by artemlazarev** [tarantool/doc#2652] opened 2022-02-01 18:54 UTC
## Info

**Root document:** At the site www.tarantool.io instaled documentation with error. At the github repo  error is fixed

## example script for file api.lua at the tutorial page https://www.tarantool.io/ru/doc/latest/getting_started/getting_started_imcp/#writing-data-5-minutes contain error at line #9

Actual :
    if err ~ = nil then
Expected:
    if err ~= nil then

**Comment by xuniq** [comment] 2022-02-02 11:52
Duplicate of #2651

**Closed by xuniq** 2022-02-02 11:52 UTC
Labels: typo
