### ISSUE TITLE
Support environment config options in documentation

### ISSUE THREAD

**Issue by Mons** [tarantool/doc#1838] opened 2021-02-16 16:41 UTC
In https://github.com/tarantool/tarantool/issues/5602 we adding support for environment variables

It should be reflected in configuration reference

**Comment by NickVolynkin** [comment] 2021-02-18 06:00
Source of inspiration: https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable

**Comment by Onvember** [comment] 2021-04-20 12:35
Duplicate of #2066

**Closed by Onvember** 2021-04-20 12:35 UTC
Labels: reference
