### ISSUE TITLE
Remove  space_object:inc/dec docs

### ISSUE THREAD

**Issue by Gerold103** [tarantool/doc#18] opened 2016-07-21 07:50 UTC
Functions inc() and dec() were removed from tarantool by https://github.com/tarantool/tarantool/issues/1289.
Need to delete them from docs:
 - https://tarantool.org/doc/book/box/box_space.html#lua-function.space_object.inc
 - https://tarantool.org/doc/book/box/box_space.html#lua-function.space_object.dec

**Comment by rtsisyk** [comment] 2016-07-21 09:27
Duplicate of #16

**Closed by rtsisyk** 2016-07-21 09:27 UTC
Labels: duplicate
