### ISSUE TITLE
Need to add the information on openSUSE packages in S3

### ISSUE THREAD

**Issue by avtikhon** [tarantool/doc#1492] opened 2020-08-31 12:28 UTC
Please add installation instructions and information on newly added opensuse-leap packages available at MCS S3 locations. Need to create new OS entry at
https://www.tarantool.io/ru/download/os-installation/docker-hub/
like "openSUSE-leap" and provide instructions as for regular RPM packages installation.

**Comment by Totktonada** [comment] 2020-08-31 12:32
Please, also support it in https://tarantool.io/installer.sh.

**Comment by artembo** [comment] 2020-08-31 12:35
@artur-barsegyan I think we do need to consider openSUSE in the new support page design.

**Comment by pgulutzan** [comment] 2020-09-01 15:36
I tried to install with my copy of openSUSE 15.

As @Totktonada mentioned earlier,
the instruction mentioned on https://www.tarantool.io/en/download/
curl -L https://tarantool.io/installer.sh | VER=2.5 sudo -E bash
gives an error message =
Unfortunately, your operating system is not supported by this script.

The instructions for building from source with RHEL/CentOS/Fedora
https://www.tarantool.io/en/doc/2.5/dev_guide/building_from_source/
fail after I say make:
No rule for make target 'build/curl/dest/lib/libcurl.a'

So maybe it is not ready to be documented in the section for
"regular RPM packages installation".

**Comment by Totktonada** [comment] 2020-09-01 16:22
It is about RPM packages repository, not about building from sources.

```
$ docker run -it opensuse/leap:15.2
(docker) # zypper install vim
(docker) # mkdir /etc/yum.repos.d/
(docker) # vim tarantool_2_5.repo  # FIXME: Provide this file using https://download.tarantool.org/<...>
(docker) # cat tarantool_2_5.repo
[tarantool_2_5]
name=openSUSE Leap 15.2 - Tarantool
baseurl=https://download.tarantool.org/tarantool/release/2.5/opensuse-leap/15.2/x86_64/
gpgkey=https://download.tarantool.org/tarantool/release/2.5/gpgkey
repo_gpgcheck=1
gpgcheck=0
enabled=1

[tarantool_2_5-source]
name=openSUSE Leap 15.2 - Tarantool Sources
baseurl=https://download.tarantool.org/tarantool/release/2.5/opensuse-leap/15.2/SRPMS
gpgkey=https://download.tarantool.org/tarantool/release/2.5/gpgkey
repo_gpgcheck=1
gpgcheck=0
(docker) # zypper addrepo tarantool_2_5.repo
(docker) # zypper refresh tarantool_2_5 tarantool_2_5-source
<...>
 - Download (curl) error for 'https://download.tarantool.org/tarantool/release/2.5/opensuse-leap/15.2/x86_64/content'
<...>
 - Download (curl) error for 'https://download.tarantool.org/tarantool/release/2.5/opensuse-leap/15.2/SRPMS/content':
```

Shame on me, I didn't verified it during review.

@avtikhon The problem is on our side. Aside of this, you didn't provide any instructions for the documentation team, just stub issue. It is not productive in most cases.

> No rule for make target 'build/curl/dest/lib/libcurl.a'

I tried to reproduce this way:

```
$ docker run -it opensuse/leap:15.2
(docker) # zypper install git
(docker) # git clone --recursive https://github.com/tarantool/tarantool.git
(docker) # cd tarantool
(docker) # zypper install cmake make gcc gcc-c++ coreutils sed readline-devel openssl-devel libicu-devel autoconf automake libtool zlib-devel zlib libunwind-devel openssl

(docker) # # (try in-source build)
(docker) # cmake . && make -j
(docker) # ./src/tarantool 
Tarantool 2.6.0-52-g71a24b9f2
type 'help' for interactive help
tarantool> 42
---
- 42
...

(docker) # # (try out-of-source build)
(docker) # git clean -xfd; git submodule foreach --recursive 'git clean -xfd'
(docker) # mkdir ../build && cd ../build
(docker) # ./src/tarantool 
Tarantool 2.6.0-52-g71a24b9f2
type 'help' for interactive help
tarantool> 42
---
- 42
...
```

@pgulutzan Please, file an issue to tarantool/tarantool with your steps to allow us to reproduce the issue.

**Comment by avtikhon** [comment] 2020-09-01 19:57
> zypper refresh tarantool_2_5 tarantool_2_5-source

Sorry, that I didn't create the example. Any way please don't use release repository as it not created currently till the first release.
The configuration file currently should be like this:
```
[tarantool_2_5]
name=openSUSE Leap 15.2 - Tarantool
baseurl=https://download.tarantool.org/tarantool/2.5/opensuse-leap/15.2/x86_64
gpgkey=https://download.tarantool.org/tarantool/2.5/gpgkey
repo_gpgcheck=1
gpgcheck=0
enabled=1

[tarantool_2_5-source]
name=openSUSE Leap 15.2 - Tarantool Sources
baseurl=https://download.tarantool.org/tarantool/2.5/opensuse-leap/15.2/SRPMS
gpgkey=https://download.tarantool.org/tarantool/2.5/gpgkey
repo_gpgcheck=1
gpgcheck=0
enabled=1
```
please use the following:
```
$ docker run -it opensuse/leap:15.2
(docker) # zypper install vim
(docker) # mkdir /etc/yum.repos.d/
(docker) # cd  /etc/yum.repos.d/
# set configuration from above
(docker) # vi tarantool_2_5.repo
# to create repo do
(docker) # zypper ar tarantool_2_5.repo 
# to search use
(docker) # zypper se tarantool
# to install use
(docker) # zypper install tarantool
```

**Comment by Totktonada** [comment] 2020-09-01 20:41
> Any way please don't use release repository as it not created currently till the first release.

Verified with 'live' repositories and it works. Sorry, I missed the fact that openSUSE support appears after the end of the previous release iteration and there are no releases built for openSUSE yet.

However it leads to the interesting question: what to do with download instructions. Possible variants:

* Restrict amount of variants on openSUSE page to `live/{1.10,2.4,2.5}` for now and expand it later to usual `{live,release}/{1.10,2.5,2.6}` (after the end of the current release iteration). @artembo How do you think, isn't this overcomplicated?
* Wait till end of the current release iteration and add it as usual.

@avtikhon How about deploy of such `tarantool_x_y.repo` files manually now (`zypper addrepo` accepts an URI) and file an issue to do this automatically for upcoming versions? Exact URIs are to be discussed, maybe `https://download.tarantool.org/<...>/release/2.5/tarantool.repo` (and `https://download.tarantool.org/<...>/2.5/tarantool.repo`) is better. Maybe it worth to split built packages and sources (to reduce metainfo traffic for a user).

@avtikhon Maybe we'll do this now? After this instructions will be really nice: no need to copy-paste repositories snippet.

@avtikhon Please, look whether there are differences with usual `/etc/yum.repos.d/*` file format: maybe we should provide something more openSUSE specific.

> (docker) # mkdir /etc/yum.repos.d/
> (docker) # cd  /etc/yum.repos.d/

It is not necessary, zypper holds its repos in `/etc/zypp/repos.d/` (`zypper addrepo` place files here, so no need to do this manually). Found `mkdir /etc/yum.repos.d/` in my steps too (forgotten to remove), removed now.

> (docker) # zypper ar tarantool_2_5.repo 
> (docker) # zypper se tarantool

Please, don't use such abbreviations in instructions.  'addrepo' and 'search' are self-descriptive, 'ar' and 'se' are not. Such abbreviations really makes understanding harder (at least for me) and I don't see any reason to use them in docs or discussions.

**Comment by avtikhon** [comment] 2020-09-02 05:17
> @avtikhon How about deploy of such `tarantool_x_y.repo` files manually now (`zypper addrepo` accepts an URI) and file an issue to do this automatically for upcoming versions? Exact URIs are to be discussed, maybe `https://download.tarantool.org/<...>/release/2.5/tarantool.repo` (and `https://download.tarantool.org/<...>/2.5/tarantool.repo`) is better. Maybe it worth to split built packages and sources (to reduce metainfo traffic for a user).
> 

I don't actually think that manual build of previous releases possible for openSUSE, due to in this way I would need to port some changes to the sources. If you don't mind about it than I'll do it.
If you meant standalone packages with Tarantool releases in naming, then I didn't understand why do you mentioned URIs with Tarantool releases in naming too - in this way we won't need it.
As about splitting packages and sources, I remember that at the very start of deploying packages we already had such discussion and that time decided to use it from different places as all other vendors do it.

> @avtikhon Maybe we'll do this now? After this instructions will be really nice: no need to copy-paste repositories snippet.
> 

I'll try to do it.

> @avtikhon Please, look whether there are differences with usual `/etc/yum.repos.d/*` file format: maybe we should provide something more openSUSE specific.
> 
> > (docker) # mkdir /etc/yum.repos.d/
> > (docker) # cd  /etc/yum.repos.d/
> 
> It is not necessary, zypper holds its repos in `/etc/zypp/repos.d/` (`zypper addrepo` place files here, so no need to do this manually). Found `mkdir /etc/yum.repos.d/` in my steps too (forgotten to remove), removed now.
> 
> > (docker) # zypper ar tarantool_2_5.repo
> > (docker) # zypper se tarantool
> 
> Please, don't use such abbreviations in instructions. 'addrepo' and 'search' are self-descriptive, 'ar' and 'se' are not. Such abbreviations really makes understanding harder (at least for me) and I don't see any reason to use them in docs or discussions.

All updated as you suggested, right above in the previous comment.

**Comment by Totktonada** [comment] 2020-09-02 07:48
> > @avtikhon How about deploy of such `tarantool_x_y.repo` files manually now (`zypper addrepo` accepts an URI) and file an issue to do this automatically for upcoming versions? Exact URIs are to be discussed, maybe `https://download.tarantool.org/<...>/release/2.5/tarantool.repo` (and `https://download.tarantool.org/<...>/2.5/tarantool.repo`) is better. Maybe it worth to split built packages and sources (to reduce metainfo traffic for a user).
> 
> I don't actually think that manual build of previous releases possible for openSUSE, due to in this way I would need to port some changes to the sources. If you don't mind about it than I'll do it.
> If you meant standalone packages with Tarantool releases in naming, then I didn't understand why do you mentioned URIs with Tarantool releases in naming too - in this way we won't need it.
> As about splitting packages and sources, I remember that at the very start of deploying packages we already had such discussion and that time decided to use it from different places as all other vendors do it.

Neither of this. I'm about .repo files available as `https://download.tarantool.org/<...>/2.5/tarantool<...>.repo`. And, yep, one for binaries, one for sources.

> cat <<EOF >/etc/zypp/repos.d/tarantool_2_5.repo
> <...>
> EOF

But why? `zypper addrepo` do this automatically. We can deploy .repo files at known URIs. So, it will be just two lines:

```
zypper addrepo https://download.tarantool.org/tarantool/2.5/opensuse-leap/15.2/x86_64/tarantool-2.5.repo
zypper addrepo https://download.tarantool.org/tarantool/2.5/opensuse-leap/15.2/SRPMS/tarantool-2.5-source.repo
```

(NB: Please, keep a file basename the same as a repository title inside.)

I looked over standard openSUSE repositories and they're named with dash separated words (and dot is not forbidden, I verified it). So I renamed the files (the repository titles assumed to be the same).

So the whole instruction will be:

**live/2.5:**

```
zypper addrepo https://download.tarantool.org/tarantool/2.5/opensuse-leap/15.2/x86_64/tarantool-2.5.repo
zypper addrepo https://download.tarantool.org/tarantool/2.5/opensuse-leap/15.2/SRPMS/tarantool-2.5-source.repo
zypper refresh --gpg-auto-import-keys tarantool-2.5 tarantool-2.5-source
zypper install tarantool
```

**release/2.5:**

```
zypper addrepo https://download.tarantool.org/tarantool/2.5/opensuse-leap/15.2/x86_64/tarantool-release-2.5.repo
zypper addrepo https://download.tarantool.org/tarantool/2.5/opensuse-leap/15.2/SRPMS/tarantool-release-2.5-source.repo
zypper refresh --gpg-auto-import-keys tarantool-release-2.5 tarantool-release-2.5-source
zypper install tarantool
```

> zypper --gpg-auto-import-keys ref

D'oh. You again push me to look at the manual. Please, don't do this. Really, I didn't ever had a thought that 'ref' is not something about references, but 'refresh'.

> autorefresh=0
> type=rpm-md

I didn't find those options in [man 5 yum.conf](https://linux.die.net/man/5/yum.conf). Is it openSUSE specific? Can you point me a document that would clarify it?

Nit: Regarding order of repository parameters: I would place most important first: name, baseurl, type (?), gpgkey, gpgcheck, repo_gpgcheck, autorefresh (?), enabled.

**Comment by avtikhon** [comment] 2020-09-02 08:27
> Neither of this. I'm about .repo files available as `https://download.tarantool.org/<...>/2.5/tarantool<...>.repo`. And, yep, one for binaries, one for sources.
> 
> > cat </etc/zypp/repos.d/tarantool_2_5.repo
> > <...>
> > EOF
> 
> But why? `zypper addrepo` do this automatically. We can deploy .repo files at known URIs. So, it will be just two lines:
> 
> ```
> zypper addrepo https://download.tarantool.org/tarantool/2.5/opensuse-leap/15.2/x86_64/tarantool-2.5.repo
> zypper addrepo https://download.tarantool.org/tarantool/2.5/opensuse-leap/15.2/SRPMS/tarantool-2.5-source.repo
> ```
> 
> (NB: Please, keep a file basename the same as a repository title inside.)
> 
> I looked over standard openSUSE repositories and they're named with dash separated words (and dot is not forbidden, I verified it). So I renamed the files (the repository titles assumed to be the same).
> 
> So the whole instruction will be:
> 
> **live/2.5:**
> 
> ```
> zypper addrepo https://download.tarantool.org/tarantool/2.5/opensuse-leap/15.2/x86_64/tarantool-2.5.repo
> zypper addrepo https://download.tarantool.org/tarantool/2.5/opensuse-leap/15.2/SRPMS/tarantool-2.5-source.repo
> zypper refresh --gpg-auto-import-keys tarantool-2.5 tarantool-2.5-source
> zypper install tarantool
> ```
> 
> **release/2.5:**
> 
> ```
> zypper addrepo https://download.tarantool.org/tarantool/2.5/opensuse-leap/15.2/x86_64/tarantool-release-2.5.repo
> zypper addrepo https://download.tarantool.org/tarantool/2.5/opensuse-leap/15.2/SRPMS/tarantool-release-2.5-source.repo
> zypper refresh --gpg-auto-import-keys tarantool-release-2.5 tarantool-release-2.5-source
> zypper install tarantool
> ```
> 

Ok, I see now what we are talking about - right, idea is really good, let's do it.

> > zypper --gpg-auto-import-keys ref
> 
> D'oh. You again push me to look at the manual. Please, don't do this. Really, I didn't ever had a thought that 'ref' is not something about references, but 'refresh'.
> 

Ok, I see, missed it, due to looked only as refresh for me.

> > autorefresh=0
> > type=rpm-md
> 
> I didn't find those options in [man 5 yum.conf](https://linux.die.net/man/5/yum.conf). Is it openSUSE specific? Can you point me a document that would clarify it?
> 
> Nit: Regarding order of repository parameters: I would place most important first: name, baseurl, type (?), gpgkey, gpgcheck, repo_gpgcheck, autorefresh (?), enabled.

This configuration was automatically updated and reworked by zypper itself, so I've put my configuration and after zypper run it was changed by zypper itself and I decided if it wants it in this style we can provide it from the very start.

**Comment by Totktonada** [comment] 2020-09-02 12:05
> This configuration was automatically updated and reworked by zypper itself, so I've put my configuration and after zypper run it was changed by zypper itself and I decided if it wants it in this style we can provide it from the very start.

Okay, I don't mind.

**Comment by avtikhon** [comment] 2020-09-02 13:26
> zypper refresh --gpg-auto-import-keys tarantool-2.5 tarantool-2.5-source

**Comment by Totktonada** [comment] 2020-09-02 13:31
@avtikhon There is no instructions regarding openSUSE on the website. The issue is not resolved. Why do you close it?

**Comment by avtikhon** [comment] 2020-09-02 13:34
> > Neither of this. I'm about .repo files available as `https://download.tarantool.org/<...>/2.5/tarantool<...>.repo`. And, yep, one for binaries, one for sources.
> > > cat </etc/zypp/repos.d/tarantool_2_5.repo
> > > <...>
> > > EOF
> > 
> > 
> > But why? `zypper addrepo` do this automatically. We can deploy .repo files at known URIs. So, it will be just two lines:
> > ```
> > zypper addrepo https://download.tarantool.org/tarantool/2.5/opensuse-leap/15.2/x86_64/tarantool-2.5.repo
> > zypper addrepo https://download.tarantool.org/tarantool/2.5/opensuse-leap/15.2/SRPMS/tarantool-2.5-source.repo
> > ```
> > 
> > 
> > (NB: Please, keep a file basename the same as a repository title inside.)
> > I looked over standard openSUSE repositories and they're named with dash separated words (and dot is not forbidden, I verified it). So I renamed the files (the repository titles assumed to be the same).
> > So the whole instruction will be:
> > **live/2.5:**
> > ```
> > zypper addrepo https://download.tarantool.org/tarantool/2.5/opensuse-leap/15.2/x86_64/tarantool-2.5.repo
> > zypper addrepo https://download.tarantool.org/tarantool/2.5/opensuse-leap/15.2/SRPMS/tarantool-2.5-source.repo
> > zypper refresh --gpg-auto-import-keys tarantool-2.5 tarantool-2.5-source
> > zypper install tarantool
> > ```
> > 
> > 
> > **release/2.5:**
> > ```
> > zypper addrepo https://download.tarantool.org/tarantool/2.5/opensuse-leap/15.2/x86_64/tarantool-release-2.5.repo
> > zypper addrepo https://download.tarantool.org/tarantool/2.5/opensuse-leap/15.2/SRPMS/tarantool-release-2.5-source.repo
> > zypper refresh --gpg-auto-import-keys tarantool-release-2.5 tarantool-release-2.5-source
> > zypper install tarantool
> > ```
> 

After investigations found this variants:
```
zypper addrepo https://download.tarantool.org/tarantool/2.5/opensuse-leap/tarantool-2.5.repo
zypper --gpg-auto-import-keys refresh -r tarantool_2.5 -r tarantool_2.5-source
zypper install tarantool
```
 (release repo still not ready ! - no packages there):
```
zypper addrepo https://download.tarantool.org/tarantool/release/2.5/opensuse-leap/tarantool-2.5.repo
zypper --gpg-auto-import-keys refresh -r tarantool_2.5 -r tarantool_2.5-source
zypper install tarantool
```

**Comment by Totktonada** [comment] 2020-09-02 16:26
I still think that explicitly separated binary and source repositories is the better choice: this way it is obvious from instructions itself how to enable just one of them. It is less obvious when we have several repos in one file.

Don't forget to replace underscores with dashes (as in file names as well as in square brackets within files).

**Comment by avtikhon** [comment] 2020-09-03 05:48
> I still think that explicitly separated binary and source repositories is the better choice: this way it is obvious from instructions itself how to enable just one of them. It is less obvious when we have several repos in one file.
> 
> Don't forget to replace underscores with dashes (as in file names as well as in square brackets within files).

All corrected.

**Closed** 2020-10-20 18:07 UTC
